name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    steps:
      - uses: ./common-step.yml

      - name: Run build
        run: npm run build
